{
 "title": "Juno stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Validator Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h3 style=\"text-align: center;\"><span style=\"color: #f0827dff;\"><span style=\"color: #f0827dff;\">Powered by</span> <a href=\"https://twitter.com/Bro_n_Bro\">Bro_n_Bro validator</a><br /><br /></span></h3>"
   }
  },
  {
   "title": "Juno Price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Juno_PRICE_total{}" }
   ]
  },
  {
   "title": "Market Cap",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Juno_Market_Cap" }
   ]
  },
  {
   "title": "APR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Juno_APR" }
   ]
  },
  {
   "title": "Inflation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Juno_INFLATION{}*100" }
   ]
  },
  {
   "title": "Active Proposals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Juno_GOV_OPEN_PROPOSALS_total{}"
    }
   ]
  },
  {
   "title": "Pending Proposals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Juno_GOV_DEPOST_PROPOSALS{}" }
   ]
  },
  {
   "title": "Max Supply",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "185562268" }
   ]
  },
  {
   "title": "Total Supply",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Juno_SUPPLY/1000000" }
   ]
  },
  {
   "title": "Circulating Supply",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Juno_Circulating_Supply" }
   ]
  },
  {
   "title": "Total amount of bonded Juno",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Juno_BONDED_TOKEN{}/1000000" }
   ]
  },
  {
   "title": "Total bonded ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Juno_Bonded_Ratio" }
   ]
  },
  {
   "title": "Community Pool",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Juno_POOL_total{}/1000000" }
   ]
  },
  {
   "title": "Last Block Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Juno_HEIGHT{}" }
   ]
  },
  {
   "title": "Current block time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds_sum{instance=\"localhost:26660\",chain_id=\"juno-1\"}/tendermint_consensus_block_interval_seconds_count{instance=\"localhost:26660\",chain_id=\"juno-1\"}"
    }
   ]
  },
  {
   "title": "Transactions per block",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "tendermint_consensus_num_txs{}" }
   ]
  },
  {
   "title": "Active Validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators{}"
    }
   ]
  }
 ]
}